# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.6
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from carbon3d.configuration import Configuration


class BuildSopsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'limit': 'int',
        'next_cursor': 'str',
        'build_sops': 'list[BuildSop]'
    }

    attribute_map = {
        'limit': 'limit',
        'next_cursor': 'next_cursor',
        'build_sops': 'build_sops'
    }

    def __init__(self, limit=None, next_cursor=None, build_sops=None, local_vars_configuration=None):  # noqa: E501
        """BuildSopsResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._limit = None
        self._next_cursor = None
        self._build_sops = None
        self.discriminator = None

        self.limit = limit
        self.next_cursor = next_cursor
        self.build_sops = build_sops

    @property
    def limit(self):
        """Gets the limit of this BuildSopsResponse.  # noqa: E501


        :return: The limit of this BuildSopsResponse.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this BuildSopsResponse.


        :param limit: The limit of this BuildSopsResponse.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and limit is None:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def next_cursor(self):
        """Gets the next_cursor of this BuildSopsResponse.  # noqa: E501

        the cursor that should be used to retrieve the next page of results  # noqa: E501

        :return: The next_cursor of this BuildSopsResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_cursor

    @next_cursor.setter
    def next_cursor(self, next_cursor):
        """Sets the next_cursor of this BuildSopsResponse.

        the cursor that should be used to retrieve the next page of results  # noqa: E501

        :param next_cursor: The next_cursor of this BuildSopsResponse.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and next_cursor is None:  # noqa: E501
            raise ValueError("Invalid value for `next_cursor`, must not be `None`")  # noqa: E501

        self._next_cursor = next_cursor

    @property
    def build_sops(self):
        """Gets the build_sops of this BuildSopsResponse.  # noqa: E501


        :return: The build_sops of this BuildSopsResponse.  # noqa: E501
        :rtype: list[BuildSop]
        """
        return self._build_sops

    @build_sops.setter
    def build_sops(self, build_sops):
        """Sets the build_sops of this BuildSopsResponse.


        :param build_sops: The build_sops of this BuildSopsResponse.  # noqa: E501
        :type: list[BuildSop]
        """
        if self.local_vars_configuration.client_side_validation and build_sops is None:  # noqa: E501
            raise ValueError("Invalid value for `build_sops`, must not be `None`")  # noqa: E501

        self._build_sops = build_sops

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildSopsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BuildSopsResponse):
            return True

        return self.to_dict() != other.to_dict()
