# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!  You can find all relevant documentation here: https://github.com/carbon3d/carbon3d-api   # noqa: E501

    The version of the OpenAPI document: 0.3.5
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from carbon3d.configuration import Configuration


class BuildPartOrders(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'part_order_number': 'str',
        'status': 'str'
    }

    attribute_map = {
        'uuid': 'uuid',
        'part_order_number': 'part_order_number',
        'status': 'status'
    }

    def __init__(self, uuid=None, part_order_number=None, status=None, local_vars_configuration=None):  # noqa: E501
        """BuildPartOrders - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._uuid = None
        self._part_order_number = None
        self._status = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if part_order_number is not None:
            self.part_order_number = part_order_number
        if status is not None:
            self.status = status

    @property
    def uuid(self):
        """Gets the uuid of this BuildPartOrders.  # noqa: E501


        :return: The uuid of this BuildPartOrders.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this BuildPartOrders.


        :param uuid: The uuid of this BuildPartOrders.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def part_order_number(self):
        """Gets the part_order_number of this BuildPartOrders.  # noqa: E501


        :return: The part_order_number of this BuildPartOrders.  # noqa: E501
        :rtype: str
        """
        return self._part_order_number

    @part_order_number.setter
    def part_order_number(self, part_order_number):
        """Sets the part_order_number of this BuildPartOrders.


        :param part_order_number: The part_order_number of this BuildPartOrders.  # noqa: E501
        :type: str
        """

        self._part_order_number = part_order_number

    @property
    def status(self):
        """Gets the status of this BuildPartOrders.  # noqa: E501


        :return: The status of this BuildPartOrders.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BuildPartOrders.


        :param status: The status of this BuildPartOrders.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildPartOrders):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BuildPartOrders):
            return True

        return self.to_dict() != other.to_dict()
