# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.6
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from carbon3d.configuration import Configuration


class PartJob(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'part_uuid': 'str',
        'status': 'str',
        'failure_reason': 'str',
        'model_uuid': 'str',
        'model_program_uuid': 'str',
        'model_program_parameters': 'dict(str, str)',
        'build_sop_uuid': 'str',
        'print_sop_uuid': 'str',
        'group_name': 'str',
        'due_date': 'datetime',
        'split_group': 'bool'
    }

    attribute_map = {
        'uuid': 'uuid',
        'part_uuid': 'part_uuid',
        'status': 'status',
        'failure_reason': 'failure_reason',
        'model_uuid': 'model_uuid',
        'model_program_uuid': 'model_program_uuid',
        'model_program_parameters': 'model_program_parameters',
        'build_sop_uuid': 'build_sop_uuid',
        'print_sop_uuid': 'print_sop_uuid',
        'group_name': 'group_name',
        'due_date': 'due_date',
        'split_group': 'split_group'
    }

    def __init__(self, uuid=None, part_uuid=None, status=None, failure_reason=None, model_uuid=None, model_program_uuid=None, model_program_parameters=None, build_sop_uuid=None, print_sop_uuid=None, group_name=None, due_date=None, split_group=True, local_vars_configuration=None):  # noqa: E501
        """PartJob - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._uuid = None
        self._part_uuid = None
        self._status = None
        self._failure_reason = None
        self._model_uuid = None
        self._model_program_uuid = None
        self._model_program_parameters = None
        self._build_sop_uuid = None
        self._print_sop_uuid = None
        self._group_name = None
        self._due_date = None
        self._split_group = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if part_uuid is not None:
            self.part_uuid = part_uuid
        if status is not None:
            self.status = status
        if failure_reason is not None:
            self.failure_reason = failure_reason
        self.model_uuid = model_uuid
        self.model_program_uuid = model_program_uuid
        self.model_program_parameters = model_program_parameters
        self.build_sop_uuid = build_sop_uuid
        self.print_sop_uuid = print_sop_uuid
        self.group_name = group_name
        self.due_date = due_date
        if split_group is not None:
            self.split_group = split_group

    @property
    def uuid(self):
        """Gets the uuid of this PartJob.  # noqa: E501


        :return: The uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this PartJob.


        :param uuid: The uuid of this PartJob.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def part_uuid(self):
        """Gets the part_uuid of this PartJob.  # noqa: E501


        :return: The part_uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._part_uuid

    @part_uuid.setter
    def part_uuid(self, part_uuid):
        """Sets the part_uuid of this PartJob.


        :param part_uuid: The part_uuid of this PartJob.  # noqa: E501
        :type: str
        """

        self._part_uuid = part_uuid

    @property
    def status(self):
        """Gets the status of this PartJob.  # noqa: E501

        PartJob status:   * `waiting` - PartJob is waiting to run.   * `model_program_running` - PartJob is running provided model program.   * `build_prep_waiting` - PartJob is waiting for build preparation step.   * `failed` - PartJob failed.   # noqa: E501

        :return: The status of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PartJob.

        PartJob status:   * `waiting` - PartJob is waiting to run.   * `model_program_running` - PartJob is running provided model program.   * `build_prep_waiting` - PartJob is waiting for build preparation step.   * `failed` - PartJob failed.   # noqa: E501

        :param status: The status of this PartJob.  # noqa: E501
        :type: str
        """
        allowed_values = ["waiting", "model_program_running", "build_prep_waiting", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def failure_reason(self):
        """Gets the failure_reason of this PartJob.  # noqa: E501

        PartJob failure reason (only present when status == `failed`):   * `unauthorized` - The request was unauthorized.   * `model_program_run` - The request failed while running a model program.   * `bad_request` - The request was malformed.   * `other` - PartJob has failed for any other reason.   # noqa: E501

        :return: The failure_reason of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason):
        """Sets the failure_reason of this PartJob.

        PartJob failure reason (only present when status == `failed`):   * `unauthorized` - The request was unauthorized.   * `model_program_run` - The request failed while running a model program.   * `bad_request` - The request was malformed.   * `other` - PartJob has failed for any other reason.   # noqa: E501

        :param failure_reason: The failure_reason of this PartJob.  # noqa: E501
        :type: str
        """
        allowed_values = ["unauthorized", "model_program_run", "bad_request", "other"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and failure_reason not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `failure_reason` ({0}), must be one of {1}"  # noqa: E501
                .format(failure_reason, allowed_values)
            )

        self._failure_reason = failure_reason

    @property
    def model_uuid(self):
        """Gets the model_uuid of this PartJob.  # noqa: E501


        :return: The model_uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._model_uuid

    @model_uuid.setter
    def model_uuid(self, model_uuid):
        """Sets the model_uuid of this PartJob.


        :param model_uuid: The model_uuid of this PartJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and model_uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `model_uuid`, must not be `None`")  # noqa: E501

        self._model_uuid = model_uuid

    @property
    def model_program_uuid(self):
        """Gets the model_program_uuid of this PartJob.  # noqa: E501


        :return: The model_program_uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._model_program_uuid

    @model_program_uuid.setter
    def model_program_uuid(self, model_program_uuid):
        """Sets the model_program_uuid of this PartJob.


        :param model_program_uuid: The model_program_uuid of this PartJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and model_program_uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `model_program_uuid`, must not be `None`")  # noqa: E501

        self._model_program_uuid = model_program_uuid

    @property
    def model_program_parameters(self):
        """Gets the model_program_parameters of this PartJob.  # noqa: E501

        parameters for the model program  # noqa: E501

        :return: The model_program_parameters of this PartJob.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._model_program_parameters

    @model_program_parameters.setter
    def model_program_parameters(self, model_program_parameters):
        """Sets the model_program_parameters of this PartJob.

        parameters for the model program  # noqa: E501

        :param model_program_parameters: The model_program_parameters of this PartJob.  # noqa: E501
        :type: dict(str, str)
        """
        if self.local_vars_configuration.client_side_validation and model_program_parameters is None:  # noqa: E501
            raise ValueError("Invalid value for `model_program_parameters`, must not be `None`")  # noqa: E501

        self._model_program_parameters = model_program_parameters

    @property
    def build_sop_uuid(self):
        """Gets the build_sop_uuid of this PartJob.  # noqa: E501


        :return: The build_sop_uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._build_sop_uuid

    @build_sop_uuid.setter
    def build_sop_uuid(self, build_sop_uuid):
        """Sets the build_sop_uuid of this PartJob.


        :param build_sop_uuid: The build_sop_uuid of this PartJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and build_sop_uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `build_sop_uuid`, must not be `None`")  # noqa: E501

        self._build_sop_uuid = build_sop_uuid

    @property
    def print_sop_uuid(self):
        """Gets the print_sop_uuid of this PartJob.  # noqa: E501


        :return: The print_sop_uuid of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._print_sop_uuid

    @print_sop_uuid.setter
    def print_sop_uuid(self, print_sop_uuid):
        """Sets the print_sop_uuid of this PartJob.


        :param print_sop_uuid: The print_sop_uuid of this PartJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and print_sop_uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `print_sop_uuid`, must not be `None`")  # noqa: E501

        self._print_sop_uuid = print_sop_uuid

    @property
    def group_name(self):
        """Gets the group_name of this PartJob.  # noqa: E501

        Group identifier  # noqa: E501

        :return: The group_name of this PartJob.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this PartJob.

        Group identifier  # noqa: E501

        :param group_name: The group_name of this PartJob.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and group_name is None:  # noqa: E501
            raise ValueError("Invalid value for `group_name`, must not be `None`")  # noqa: E501

        self._group_name = group_name

    @property
    def due_date(self):
        """Gets the due_date of this PartJob.  # noqa: E501

        Print due date, used to prioritize Part Jobs  # noqa: E501

        :return: The due_date of this PartJob.  # noqa: E501
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date):
        """Sets the due_date of this PartJob.

        Print due date, used to prioritize Part Jobs  # noqa: E501

        :param due_date: The due_date of this PartJob.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and due_date is None:  # noqa: E501
            raise ValueError("Invalid value for `due_date`, must not be `None`")  # noqa: E501

        self._due_date = due_date

    @property
    def split_group(self):
        """Gets the split_group of this PartJob.  # noqa: E501

        Allows a part_group to be split across multiple builds.  # noqa: E501

        :return: The split_group of this PartJob.  # noqa: E501
        :rtype: bool
        """
        return self._split_group

    @split_group.setter
    def split_group(self, split_group):
        """Sets the split_group of this PartJob.

        Allows a part_group to be split across multiple builds.  # noqa: E501

        :param split_group: The split_group of this PartJob.  # noqa: E501
        :type: bool
        """

        self._split_group = split_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PartJob):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PartJob):
            return True

        return self.to_dict() != other.to_dict()
