# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.17
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import carbon3d
from carbon3d.models.string_parameter import StringParameter  # noqa: E501
from carbon3d.rest import ApiException

class TestStringParameter(unittest.TestCase):
    """StringParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StringParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = carbon3d.models.string_parameter.StringParameter()  # noqa: E501
        if include_optional :
            return StringParameter(
                key = 'MODEL_UUID', 
                type = 'string', 
                value = '00000000-0000-0000-0000-000000000000'
            )
        else :
            return StringParameter(
                key = 'MODEL_UUID',
                value = '00000000-0000-0000-0000-000000000000',
        )

    def testStringParameter(self):
        """Test StringParameter"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
