# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!  You can find all relevant documentation here: https://github.com/carbon3d/carbon3d-api   # noqa: E501

    The version of the OpenAPI document: 0.3.5
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import carbon3d
from carbon3d.models.printer_prints import PrinterPrints  # noqa: E501
from carbon3d.rest import ApiException

class TestPrinterPrints(unittest.TestCase):
    """PrinterPrints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PrinterPrints
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = carbon3d.models.printer_prints.PrinterPrints()  # noqa: E501
        if include_optional :
            return PrinterPrints(
                last = carbon3d.models.print_ref.PrintRef(
                    name = '0', 
                    print_id = '0', 
                    build_uuid = '0', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    remaining_sec = 56, ), 
                current = carbon3d.models.print_ref.PrintRef(
                    name = '0', 
                    print_id = '0', 
                    build_uuid = '0', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    remaining_sec = 56, ), 
                next = carbon3d.models.print_ref.PrintRef(
                    name = '0', 
                    print_id = '0', 
                    build_uuid = '0', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    remaining_sec = 56, ), 
                queue_length = 56
            )
        else :
            return PrinterPrints(
                queue_length = 56,
        )

    def testPrinterPrints(self):
        """Test PrinterPrints"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
