# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.6
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import carbon3d
from carbon3d.models.build_sops_response import BuildSopsResponse  # noqa: E501
from carbon3d.rest import ApiException

class TestBuildSopsResponse(unittest.TestCase):
    """BuildSopsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BuildSopsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = carbon3d.models.build_sops_response.BuildSopsResponse()  # noqa: E501
        if include_optional :
            return BuildSopsResponse(
                limit = 1, 
                next_cursor = 'dXNlcjpXMDdRQ1JQQTQ=', 
                build_sops = [
                    carbon3d.models.build_sop_request.BuildSop request(
                        uuid = '0d16d62d-f09a-4bb9-895f-b039b2b26802', 
                        name = 'Main Production', 
                        description = 'Generates builds for main production', 
                        build_prefix = 'AutoBuild#', 
                        resin_name = 'DPR 10', 
                        print_profile = 'Default', 
                        release_film = True, 
                        layout_profile = 'denser', 
                        layout_padding_mm = 1, )
                    ]
            )
        else :
            return BuildSopsResponse(
                limit = 1,
                next_cursor = 'dXNlcjpXMDdRQ1JQQTQ=',
                build_sops = [
                    carbon3d.models.build_sop_request.BuildSop request(
                        uuid = '0d16d62d-f09a-4bb9-895f-b039b2b26802', 
                        name = 'Main Production', 
                        description = 'Generates builds for main production', 
                        build_prefix = 'AutoBuild#', 
                        resin_name = 'DPR 10', 
                        print_profile = 'Default', 
                        release_film = True, 
                        layout_profile = 'denser', 
                        layout_padding_mm = 1, )
                    ],
        )

    def testBuildSopsResponse(self):
        """Test BuildSopsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
