# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.6
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import carbon3d
from carbon3d.api.print_sops_api import PrintSopsApi  # noqa: E501
from carbon3d.rest import ApiException


class TestPrintSopsApi(unittest.TestCase):
    """PrintSopsApi unit test stubs"""

    def setUp(self):
        self.api = carbon3d.api.print_sops_api.PrintSopsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_print_sop(self):
        """Test case for create_print_sop

        Creates a PrintSop  # noqa: E501
        """
        pass

    def test_delete_print_sop(self):
        """Test case for delete_print_sop

        Deletes a PrintSop  # noqa: E501
        """
        pass

    def test_get_print_sops(self):
        """Test case for get_print_sops

        Gets all PrintSops  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
