# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.17
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import carbon3d
from carbon3d.api.print_quality_data_api import PrintQualityDataApi  # noqa: E501
from carbon3d.rest import ApiException


class TestPrintQualityDataApi(unittest.TestCase):
    """PrintQualityDataApi unit test stubs"""

    def setUp(self):
        self.api = carbon3d.api.print_quality_data_api.PrintQualityDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_print_quality_data(self):
        """Test case for get_print_quality_data

        List finished print's quality metrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
