# coding: utf-8

"""
    Carbon DLS API

    Welcome to the Carbon DLS API docs!   # noqa: E501

    The version of the OpenAPI document: 0.4.16
    Contact: api-list@carbon3d.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import carbon3d
from carbon3d.models.model_program_runs import ModelProgramRuns  # noqa: E501
from carbon3d.rest import ApiException

class TestModelProgramRuns(unittest.TestCase):
    """ModelProgramRuns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ModelProgramRuns
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = carbon3d.models.model_program_runs.ModelProgramRuns()  # noqa: E501
        if include_optional :
            return ModelProgramRuns(
                model_program_runs = [
                    {"uuid":"63db11ee-a130-4ddf-b3d2-ab2c5d1852ed","status":"complete","progress":1,"model_uuid":"3427f879-4a36-409a-b09c-4196cb2f5cd0","failure_message":null,"operation_status":[{"external_id":"operation_external_id","status":"complete","progress":1,"model_uuid":"3427f879-4a36-409a-b09c-4196cb2f5cd0","failure_message":null}]}
                    ]
            )
        else :
            return ModelProgramRuns(
                model_program_runs = [
                    {"uuid":"63db11ee-a130-4ddf-b3d2-ab2c5d1852ed","status":"complete","progress":1,"model_uuid":"3427f879-4a36-409a-b09c-4196cb2f5cd0","failure_message":null,"operation_status":[{"external_id":"operation_external_id","status":"complete","progress":1,"model_uuid":"3427f879-4a36-409a-b09c-4196cb2f5cd0","failure_message":null}]}
                    ],
        )

    def testModelProgramRuns(self):
        """Test ModelProgramRuns"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
